# Generated by Django 3.2.11 on 2022-04-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipImo', models.IntegerField()),
                ('shipName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ShipLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logDate', models.DateField()),
                ('logTime', models.TimeField()),
                ('logCategory', models.CharField(max_length=10)),
                ('logDescription', models.CharField(max_length=100)),
                ('logExtranote', models.CharField(max_length=50)),
                ('logImo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mclogapp.shipdetails')),
            ],
        ),
    ]
