# Generated by Django 3.2.11 on 2022-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mclogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiplogs',
            options={'ordering': ['logDate']},
        ),
        migrations.AlterField(
            model_name='shipdetails',
            name='shipImo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='shiplogs',
            name='logCategory',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shiplogs',
            name='logExtranote',
            field=models.CharField(max_length=100),
        ),
    ]
